### Задание 1

In [1]:
import numpy as np

In [109]:
a = np.reshape((1, 2, 3, 3, 1, 6, 8, 11, 10, 7),(5,2))
a

array([[ 1,  2],
       [ 3,  3],
       [ 1,  6],
       [ 8, 11],
       [10,  7]])

In [123]:
a_mean = a.mean(axis = 0)
a_mean

array([4.6, 5.8])

### Задание 2

In [125]:
a_centered = a - a_mean
a_centered

array([[-3.6, -3.8],
       [-1.6, -2.8],
       [-3.6,  0.2],
       [ 3.4,  5.2],
       [ 5.4,  1.2]])

### Задание 3

In [130]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]
a_centered_sp

41.60000000000001

In [135]:
a_centered_sp / (a_centered.shape[0] - 1)

10.400000000000002